name: Deploy Documentation

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

# Set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  id-token: write
  pages: write

# Allow one concurrent deployment. Do not cancel in-flight deployments because we don't want assets to be in a
# a semi-deployed state.
concurrency: 
  group: "deploy-documentation"
  cancel-in-progress: false

jobs:
  deploy-documentation:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up GitHub Pages
        uses: actions/configure-pages@v3
      - name: Build Documentation
        run: |
          xcodebuild docbuild \
            -scheme sort-state-university \
            -derivedDataPath /tmp/DerivedData \
            -destination 'generic/platform=iOS';
          mkdir _site;
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/DerivedData/Build/Products/Debug-iphoneos/SortStateUniversity.doccarchive \
            --hosting-base-path sort-state-university \
            --output-path _site;
      - name: Create index.html
        run: |
          echo "<script>window.location.href += \"documentation/sortstateuniversity\"</script>" > _site/index.html;
      - name: Upload Documentation Artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v1
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2