# - macOS Image Resources: https://github.com/actions/virtual-environments/tree/main/images/macos

name: Test

on:
  push:
  pull_request:
    branches:
      - "**:**" # PRs from forks have a prefix with `owner:`

jobs:
  get-environment-details:
    name: Get Environment Details
    runs-on: macOS-10.15
    strategy:
          matrix:
            xcode:
              - "12.0.1"
              - "12.1"
              - "12.2"
              - "12.3"
              - "12.4"
    steps:
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Print OS SDKs
        run: xcodebuild -version -sdk

      - name: Print simulators
        run: |
          xcrun simctl delete unavailable
          xcrun simctl list
  
  test-iOS:
      name: Test on iOS 14
      runs-on: macOS-10.15
      strategy:
          matrix:
            # We assume that Xcode minor version == iOS minor version
            destination: 
              - "name=iPhone 11 Pro"
            xcode:
              - "12.0.1"
              - "12.1"
              - "12.2"
              - "12.3"
              - "12.4"
      steps:
        - name: Checkout project
          uses: actions/checkout@master

        - name: Select Xcode ${{ matrix.xcode }}
          run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

        - name: Run tests
          run: |
            set -o pipefail
            xcodebuild clean test -scheme sort-state-university -sdk iphonesimulator -destination "${{ matrix.destination }}" -configuration Debug -enableCodeCoverage YES | xcpretty -c

        - name: Upload code coverage
          uses: codecov/codecov-action@v1
          with:
            fail_ci_if_error: true

  test-macOS:
    name: Test on macOS 10.15
    runs-on: macOS-10.15
    steps:
      - name: Checkout Project
        uses: actions/checkout@master

      - name: Run Tests
        run: swift test

  test-tvOS:
    name: Test on tvOS 14
    runs-on: macOS-10.15
    strategy:
        matrix:
          # We assume that Xcode minor version == tvOS minor version
          destination: 
            - "name=Apple TV 4K"
          xcode:
            - "12.0.1"
            - "12.1"
            - "12.2"
            - "12.3"
    steps:
      - name: Checkout project
        uses: actions/checkout@master

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Run tests
        run: |
          set -o pipefail
          xcodebuild clean test -scheme sort-state-university -sdk appletvsimulator -destination "${{ matrix.destination }}" -configuration Debug -enableCodeCoverage YES | xcpretty -c

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
      
  # test-watchOS:
  #   name: Build for watchOS 7
  #   runs-on: macOS-10.15
  #   strategy:
  #       matrix:
  #         destination: 
  #           - "name=Apple Watch Series 6 - 44mm"
  #         xcode:
  #           - "12.4"
  #   steps:
  #     - name: Checkout project
  #       uses: actions/checkout@master

  #     - name: Select Xcode ${{ matrix.xcode }}
  #       run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app

  #     - name: Run tests
  #       run: |
  #         set -o pipefail
  #         xcodebuild -scheme sort-state-university -destination "${{ matrix.destination }}" -configuration Debug build | xcpretty -c